target: 161044070

161044070: main.cpp BoardAbstract.h BoardAbstract.cpp BoardVector.h BoardVector.cpp BoardArray2D.h BoardArray2D.cpp BoardArray1D.h BoardArray1D.cpp GlobalFunction.h Namespace.h
	g++ -std=c++11 main.cpp BoardAbstract.h BoardAbstract.cpp BoardVector.h BoardVector.cpp BoardArray2D.h BoardArray2D.cpp BoardArray1D.h BoardArray1D.cpp GlobalFunction.h Namespace.h -o 161044070

clean:
	rm 161044070